### PR TITLE
Solved issue #52

### PR DESCRIPTION
**Pull request by adrianmarinwork**
Fixed issue #52 

Notes:
I don't know if you remember, but I asked you to take care of the issue related to the translation of the app to Spanish, I've taken the freedom to improve some texts that were a bit misunderstood.

If you need anything just tell me!

### CODE REVIEW

**Comment by samc18** [comment]
hi @adrianmarinwork, I do remember! Thanks for taking the time to go above and beyond! Your changes are looking great! Do you mind also updating the final message after clicking "Check My Finances!" to take into account the new savings logic? 

For example, here the final message (Spanish and English) should take into account that savings should be at least or above the max amount instead of less.
image

Really sorry for the delay!

**Comment by adrianmarinwork** [comment]
Yeah, the case of savings goes in a different way than the other two fields, so the texts should change, let me change them!

**Comment by adrianmarinwork** [comment]
The changes you asked for should be running and working fine, if you need anything else tell me!

**Comment by adrianmarinwork** [comment]
Shit, I made a mistake hahaha, can you change the under I show in the screenshot for "over" when you merge de pull request pls?

image

**Comment by samc18** [comment]
hi @adrianmarinwork changes are looking great!

I can't modify your PR directly you will need to grant me access. More info here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

I think it will be a better idea if you just commit that quick fix to your branch in order to follow the proper GitHub flow. That's the only thing left.

**Comment by adrianmarinwork** [comment]
Do you mean the "over or equal" change? You can merge the pull request as is it right now and then add the change, but if you prefer I can create a commit with the change too!

**Comment by adrianmarinwork** [comment]
There you go I have added the commit, feel free to merge the pull request if you see that everything is fine!

**Comment by samc18** [comment]
Everything looks great! Thanks for taking the time to help out with this project!

**Pull request merged**
