### PR TITLE
improve clickable elements and layout of fundamental page

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## Fix issue
[BUG] Fix links #51 [](https://github.com/samc18/my-finances-checker/issues/51)

## Changes proposed
1. Made clickable elements like buttons and links look interactive by implementing animation and other hover effects.
2. Improved the layout of the fundamentals page by providing a card-like structure for the 50/30/20 rule.

## Screenshots

**Button Hover:**

Recording 2022-12-24 at 00 57 22

**The layout of Fundamental page:**

#51

### CODE REVIEW

**Comment by samc18** [comment]
hi, @AlfiyaSiddique amazing work! I'm truly amazed about the animations implemented and how you improved the Fundamentals layout! It's looking way better than before! 

I think you are using a previous version of the project, do you mind pulling the latest changes? For example, you are missing the language feature.

I have a few quick notes:

1. There is a bit of an issue with overflowing text around 700px.
image

2. The icons to open modals and the button to add an income or expense ideally should also have something else than the cursor to point them as clickable elements. What are your thoughts on this?
image

4. The Welcome and Check My Finances Button are changing their size a bit when hovering over them, my guess is that the difference is coming from the new border being added in the hover effect since initially, neither of the buttons had borders. Is this the expected behavior?

Thanks for the amazing work!

**Comment by AlfiyaSiddique** [comment]
Hello **@samc18**  
I will pull the latest changes, thanks for drawing my attention.

And about the other queries:
1. I will quickly look into the overflowing text issue and fix it.
2. As the add button and the other icon are small elements, so I think changing the color shades during the hover state will look good.
3. Yes, the change in the size of the buttons on hover is the expected behavior and you guessed the reason right, it is because I added the border which appears only during the hovering state.  If you think the button size should be the same during the hover state, let me know so I can modify it.

I'm glad that the changes made are helpful
Thank you!

**Comment by samc18** [comment]
hi @AlfiyaSiddique with regards to point number 3, since is just the borders I think it would be better if they don't change the size, a personal thing to be honest nothing wrong with it!

**Comment by AlfiyaSiddique** [comment]
Okay **@samc18**, 
I'll go with your opinion and will do the changes 👍🏻.

**Comment by AlfiyaSiddique** [comment]
Hi **@samc18** 

I analyzed the code again, the button size was changing because of the increased font weight so I removed that property, and the rest of the design is the same. Now, the issue of button increased size on hover is solved

**Comment by samc18** [comment]
hi @AlfiyaSiddique awesome work on the clickable elements! There is still a bit of an issue around 800-900 px with the Monthly Income card. 
image

On another note, I believe that you are using a previous Fundamentals version of the code since is not receiving the component to translate the text.

Sorry for the delay.

**Comment by AlfiyaSiddique** [comment]
Hi **@samc18** 

How can I change my fundamentals to the current version because it is saying that my branch is up to date? Please guide me with this.

**Comment by samc18** [comment]
hi @AlfiyaSiddique I reviewed your latest changes, and everything is looking great! Amazing work thank you for taking the time to be part of this project!

**Pull request merged**
